# Generated by Django 4.2.9 on 2024-01-25 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.CharField(max_length=2)),
                ('start', models.DateField()),
                ('plan', models.CharField(max_length=255)),
                ('value', models.FloatField()),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
