# Generated by Django 4.2.9 on 2024-01-25 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('value', models.FloatField()),
                ('paid', models.CharField(choices=[('À pagar', 'À pagar'), ('Pago', 'Pago')], default='À pagar', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
