name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Substitua pelo nome do branch principal do seu repositório

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout do código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Use a versão adequada para o seu projeto

      # 3. Instalar dependências
      - name: Install dependencies
        run: npm install

      # 4. Gerar o build
      - name: Build project
        run: npm run build

      # 5. Deploy para GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist # Publicar a pasta dist gerada